# Generated by Django 4.2.3 on 2023-07-15 08:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehousesection',
            old_name='section',
            new_name='max_sub_sections',
        ),
        migrations.AddField(
            model_name='monitoringdata',
            name='report_remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitoringdata',
            name='unit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='monitoringdevice',
            name='mac_address',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='monitoringdevice',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='warehousesection',
            name='area',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='warehousesection',
            name='cc_camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cccamera_monitoringdevice', to='inventory.monitoringdevice', verbose_name='CC Camera'),
        ),
        migrations.CreateModel(
            name='StorageManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_mfg_id', models.PositiveIntegerField()),
                ('product_digital_twin', models.URLField()),
                ('sub_section', models.PositiveIntegerField()),
                ('booked_from', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='From Date')),
                ('booked_to', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='To Date')),
                ('booked_by', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Stored', 'Stored'), ('Returned', 'Returned'), ('Clear', 'Clear'), ('Archived', 'Archived')], default='Stored', max_length=20)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_monitoringdevice', to='inventory.warehousesection')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_inventorydetail', to='inventory.inventorydetail')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
