version: '3'
volumes:
  peer${PEER_COUNT}.${ORG_NAME}.${DOMAIN_ADDRESS}:
networks:
  ${NETWORK_NAME}:
    name: ${NETWORK_NAME}
services:
  peer${PEER_COUNT}.${ORG_NAME}.${DOMAIN_ADDRESS}:
    container_name: peer${PEER_COUNT}.${ORG_NAME}.${DOMAIN_ADDRESS}
    image: hyperledger/fabric-peer:latest
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK_NAME}
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer${PEER_COUNT}.${ORG_NAME}.${DOMAIN_ADDRESS}
      - CORE_PEER_ADDRESS=peer${PEER_COUNT}.${ORG_NAME}.${DOMAIN_ADDRESS}:${CORE_PEER_PORT}
      - CORE_PEER_LISTENADDRESS=0.0.0.0:${CORE_PEER_PORT}
      - CORE_PEER_CHAINCODEADDRESS=peer${PEER_COUNT}.${ORG_NAME}.${DOMAIN_ADDRESS}:${CORE_PEER_CHAINCODE_LISTEN_PORT}
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:${CORE_PEER_CHAINCODE_LISTEN_PORT}
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer${PEER_COUNT}.${ORG_NAME}.${DOMAIN_ADDRESS}:${CORE_PEER_PORT}
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer${PEER_COUNT}.${ORG_NAME}.${DOMAIN_ADDRESS}:${CORE_PEER_PORT}
      - CORE_PEER_LOCALMSPID=${ORGANIZATION_NAME}MSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:${LISTEN_PEER_PORT}
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../../organizations/peerOrganizations/${ORG_NAME}.${DOMAIN_ADDRESS}/peers/peer${PEER_COUNT}.${ORG_NAME}.${DOMAIN_ADDRESS}/msp:/etc/hyperledger/fabric/msp
      - ../../organizations/peerOrganizations/${ORG_NAME}.${DOMAIN_ADDRESS}/peers/peer${PEER_COUNT}.${ORG_NAME}.${DOMAIN_ADDRESS}/tls:/etc/hyperledger/fabric/tls
      - peer${PEER_COUNT}.${ORG_NAME}.${DOMAIN_ADDRESS}:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - ${CORE_PEER_PORT}:${CORE_PEER_PORT}
      - ${LISTEN_PEER_PORT}:${LISTEN_PEER_PORT}
    networks:
      - ${NETWORK_NAME}
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer${PEER_COUNT}.${ORG_NAME}.${DOMAIN_ADDRESS}
    networks:
      - ${NETWORK_NAME}