# Generated by Django 4.2.3 on 2023-07-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_blockchain_manager', '0002_rename_sign_domain_id_ethsignature_sign_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcontractdeployment',
            name='network_title',
            field=models.CharField(default='23-07-15 04:23:40.988796', max_length=20),
            preserve_default=False,
        ),
    ]
