# Generated by Django 4.2.3 on 2023-07-15 14:39

import datetime
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public_blockchain_manager', '0003_smartcontractdeployment_network_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_organizer', models.CharField(max_length=100)),
                ('applicant_wallet', models.CharField(max_length=42)),
                ('endorsement_office', models.CharField(max_length=100)),
                ('endorsement_organization', models.CharField(max_length=100)),
                ('endorsement_org_wallet', models.CharField(max_length=42)),
                ('valid_from_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Start Date')),
                ('valid_to_date', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='End Date')),
                ('token_id', models.CharField(max_length=255)),
                ('mfg_license', models.CharField(max_length=100)),
                ('gateway_url', models.URLField()),
                ('private_ledger_id', models.CharField(max_length=200)),
                ('access_type', models.CharField(choices=[('READ ONLY', 'READ ONLY'), ('WRITE', 'WRITE')], default='READ ONLY', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
