# Generated by Django 4.2.3 on 2023-07-15 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('public_blockchain_manager', '0004_accessrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='applicant_organizer',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='token_id',
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='applicant_organization',
            field=models.CharField(default='X', max_length=100, verbose_name='Organization'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='digital_twin_url',
            field=models.URLField(default='www.example.com', verbose_name='Digital Twin URL'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='mfg_id',
            field=models.CharField(default='#Sample', max_length=100, verbose_name='MFG. ID'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='signature_request_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='smart_contract_address',
            field=models.CharField(default='0x......', max_length=42),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='applicant_name',
            field=models.CharField(default='Mr. X', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='applicant_wallet',
            field=models.CharField(default='0x...', max_length=42, verbose_name='Wallet Address'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='endorsement_office',
            field=models.CharField(default='Mr. Y', max_length=100, verbose_name='Officer Name'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='endorsement_org_wallet',
            field=models.CharField(default='0x...', max_length=42, verbose_name='Wallet Address'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='endorsement_organization',
            field=models.CharField(default='Y', max_length=100, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='gateway_url',
            field=models.URLField(default='http://localhost:8000/', verbose_name='Gateway URL'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='mfg_license',
            field=models.CharField(default='#Lis123', max_length=200, verbose_name='MFG. License'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='private_ledger_id',
            field=models.CharField(default='hlf-pk', max_length=200),
        ),
    ]
