# Generated by Django 4.2.3 on 2023-07-14 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('certification_title', models.CharField(max_length=50)),
                ('certification_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('designation', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ManufacturerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo')),
                ('tin_number', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(max_length=500)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProductTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('chassis_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Minivan', 'Minivan-MPV'), ('Hatchback', 'Hatchback-MPV'), ('Pickup', 'Pickup'), ('FreezerVan', 'Freezer Van'), ('CoveredVan', 'Covered Van'), ('Truck', 'Truck')], default='Sedan', max_length=20)),
                ('fuel_type', models.CharField(choices=[('Hybrid', 'Hybrid'), ('LeadAcid', 'Lead Acid'), ('LithiumIronPhosphate', 'Lithium Iron Phosphate'), ('Octane/CNG', 'Octane/CNG'), ('Octane', 'Octane')], default='Hybrid', max_length=20)),
                ('seat_number', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('Black', 'Black'), ('Silver', 'Silver'), ('White', 'White'), ('Red', 'Red')], default='White', max_length=20)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('owner_address', models.CharField(max_length=64)),
                ('mfg_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mfg_license', models.CharField(max_length=100)),
                ('digital_twin', models.BooleanField(default=False)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_manufacturer', to='manufacturer.manufacturerdetail')),
                ('manufacturing_team', models.ManyToManyField(to='manufacturer.employeedetail')),
                ('trait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trait_producttrait', to='manufacturer.producttrait')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_employer', to='manufacturer.manufacturerdetail'),
        ),
    ]
