# Generated by Django 4.2.3 on 2023-07-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='manufacturing_team',
            field=models.ManyToManyField(blank=True, to='manufacturer.employeedetail'),
        ),
    ]
