# Generated by Django 4.2.3 on 2023-07-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0004_productdetail_image_alter_employeedetail_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='mfg_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
