Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        SkipAsForeign: false
        ID: OrdererMSP
        MSPDir: ../../../organizations/ordererOrganizations/brainstation23.com/msp
        Policies: &OrdererOrgPolicies
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
            # Endorsement:
            #     Type: Signature
            #     Rule: "OR('OrdererMSP.peer')"

        OrdererEndpoints:
            - orderer.brainstation23.com:7050
    - &Teq
        Name: TeqMSP
        ID: TeqMSP
        MSPDir: ../../../organizations/peerOrganizations/teq.brainstation23.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('TeqMSP.admin', 'TeqMSP.peer', 'TeqMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('TeqMSP.admin', 'TeqMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('TeqMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('TeqMSP.peer')"
    - &Fardia
        Name: FardiaMSP
        ID: FardiaMSP
        MSPDir: ../../../organizations/peerOrganizations/fardia.brainstation23.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('FardiaMSP.admin', 'FardiaMSP.peer', 'FardiaMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('FardiaMSP.admin', 'FardiaMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('FardiaMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('FardiaMSP.peer')"

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 500
        AbsoluteMaxBytes: 10 MB
        PreferredMaxBytes: 2 MB
    MaxChannels: 0

    Addresses:
      - orderer.brainstation23.com:7050

    EtcdRaft:
        Consenters:
          - Host: orderer.brainstation23.com
            Port: 7050
            ClientTLSCert: ../../../organizations/ordererOrganizations/brainstation23.com/orderers/orderer.brainstation23.com/tls/server.crt
            ServerTLSCert: ../../../organizations/ordererOrganizations/brainstation23.com/orderers/orderer.brainstation23.com/tls/server.crt

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

    Capabilities:
        <<: *OrdererCapabilities

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:
    OrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            Organizations:
              - <<: *OrdererOrg

        Consortiums:
            BasicConsortium:
                Organizations:
                    - <<: *Teq
                    - <<: *Fardia
    BasicChannel:
            Consortium: BasicConsortium
            <<: *ChannelDefaults
            Application:
                <<: *ApplicationDefaults
                Organizations:
                    - *Teq
                    - *Fardia

                Capabilities:
                    <<: *ApplicationCapabilities